### ISSUE TITLE
elastic search error

### ISSUE THREAD

**Issue by wolffles** [wolffles/StayFreshers#22]
hey britt, 
https://github.com/wolffles/StayFreshers/tree/refining link to the branch with elastic search.

all our efforts failed with an error: "notes does not exist to be imported into. Use create_index! or the :force option to create it"

we couldn't force create an index either.

**Comment by brittanyjspringer** [comment]
@wolffles I'm going to re-assign to you. Can you please set up a solid Seeds file that has confirmed users with TestSets, Notes etc. so I can easily take a look at the error? Thanks!
